-- MySQL Script generated by MySQL Workbench
-- ter 06 set 2022 19:21:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Departamento_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Funcionario_Departamento_idx` (`Departamento_codigo` ASC) VISIBLE,
  CONSTRAINT `FK_FUN_DEPT`
    FOREIGN KEY (`Departamento_codigo`)
    REFERENCES `mydb`.`Departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `Sigla` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Area_Sigla` INT NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Area_Area1_idx` (`Area_Sigla` ASC) VISIBLE,
  CONSTRAINT `FK_AREA_SUPERAREA`
    FOREIGN KEY (`Area_Sigla`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Sigla` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` DATETIME NULL,
  `Custo` DOUBLE NULL,
  `Area_Sigla` INT NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Cursos_Area1_idx` (`Area_Sigla` ASC) VISIBLE,
  CONSTRAINT `FK_CURSO_AREA`
    FOREIGN KEY (`Area_Sigla`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modulo` (
  `Sigla` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Cursos_Sigla` INT NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Modulo_Cursos1_idx` (`Cursos_Sigla` ASC) VISIBLE,
  CONSTRAINT `FK_MODULO_CURSO`
    FOREIGN KEY (`Cursos_Sigla`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topico` (
  `Sigla` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` DATETIME NULL,
  `Modulo_Sigla` INT NOT NULL,
  PRIMARY KEY (`Sigla`, `Modulo_Sigla`),
  INDEX `fk_Topico_Modulo1_idx` (`Modulo_Sigla` ASC) VISIBLE,
  CONSTRAINT `FK_TOPICO_MODULO`
    FOREIGN KEY (`Modulo_Sigla`)
    REFERENCES `mydb`.`Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Sexo` CHAR(1) NULL,
  `DataNasc` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `Cursos_Sigla` INT NOT NULL,
  `Aluno_CPF` CHAR(11) NOT NULL,
  `Data` DATE NULL,
  `Pago` TINYINT NULL,
  PRIMARY KEY (`Cursos_Sigla`, `Aluno_CPF`),
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno_CPF` ASC) VISIBLE,
  CONSTRAINT `FK_MATRICULA_CURSO`
    FOREIGN KEY (`Cursos_Sigla`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MATRICULA_ALUNO`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Curso_Sigla` INT NOT NULL,
  PRIMARY KEY (`CPF`, `Curso_Sigla`),
  INDEX `fk_Professor_Curso1_idx` (`Curso_Sigla` ASC) VISIBLE,
  CONSTRAINT `FK_PROFESSOR_CURSO`
    FOREIGN KEY (`Curso_Sigla`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
