/*
	GABRIEL MARTINS PEREIRA - 733875
    CIÊNCIAS DA COMPUTAÇÃO
*/

CREATE SCHEMA SAM_SCHEMA;
CREATE DATABASE SAM_DB;
USE SAM_DB;

CREATE TABLE CURSO (
    SIGLA VARCHAR(4) NOT NULL,
    NOME VARCHAR(45) NULL,
    HORAS DATETIME NULL,
    CUSTO DOUBLE NULL)
ENGINE = InnoDB;

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (SIGLA);
ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO_AREA 
FOREIGN KEY (AREA) REFERENCES AREA(SIGLA) 
ON DELETE SET NULL ON UPDATE CASCADE;
 
CREATE TABLE AREA (
	SIGLA VARCHAR(4) NOT NULL,
    NOME VARCHAR(45) NULL)
ENGINE = InnoDB;
 
ALTER TABLE AREA ADD CONSTRAINT PK_AREA PRIMARY KEY(SIGLA);
ALTER TABLE AREA ADD CONSTRAINT FK_AREA_SUPERAREA 
FOREIGN KEY (SUPERAREA) REFERENCES AREA(SIGLA)
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE PROFESSOR (
	CPF VARCHAR(4) UNIQUE NOT NULL,
    NOME VARCHAR(45) NULL)
ENGINE = InnoDB;

ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_CURSO 
FOREIGN KEY (CURSO) REFERENCES CURSO(SIGLA) 
ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(CPF);
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR_CURSO PRIMARY KEY(CURSO);

CREATE TABLE MODULO (
	SIGLA VARCHAR(4) NOT NULL,
    NOME VARCHAR(45) NULL) 
ENGINE = InnoDB;

ALTER TABLE MODULO ADD CONSTRAINT PK_MODULO PRIMARY KEY(SIGLA);
ALTER TABLE MODULO ADD CONSTRAINT FK_MODULO_CURSO
FOREIGN KEY (CURSO) REFERENCES CURSO(SIGLA)
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE TOPICO (
	SIGLA VARCHAR(4) NOT NULL,
    NOME VARCHAR(45) NULL,
    HORAS DATETIME NULL) 
ENGINE = InnoDB;

ALTER TABLE TOPICO ADD CONSTRAINT FK_TOPICO_MODULO
FOREIGN KEY (MODULO) REFERENCES MODULO(SIGLA)
ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE TOPICO ADD CONSTRAINT PK_TOPICO PRIMARY KEY(SIGLA);
ALTER TABLE TOPICO ADD CONSTRAINT PK_TOPICO_MODULO PRIMARY KEY(MODULO);

CREATE TABLE ALUNO (
	CPF CHAR(11) UNIQUE NOT NULL,
    NOME VARCHAR(45) NULL,
    SOBRENOME VARCHAR(45) NULL,
    SEXO CHAR(1) NULL,
    DATANASC DATE NULL) 
ENGINE = InnoDB;

ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO PRIMARY KEY(CPF);

CREATE TABLE MATRICULA (
	DATAMAT DATE NULL,
	PAGO TINYINT NULL) 
ENGINE = InnoDB;

ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_ALUNO
FOREIGN KEY (ALUNO) REFERENCES ALUNO(CPF)
ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_CURSO
FOREIGN KEY (CURSO) REFERENCES CURSO(SIGLA)
ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE MATRICULA ADD CONSTRAINT PK_MATRICULA_ALUNO PRIMARY KEY(ALUNO);
ALTER TABLE MATRICULA ADD CONSTRAINT PK_MATRICULA_CURSO PRIMARY KEY(CURSO);
